services:
  - type: web
    name: watch-inventory-server
    env: node
    rootDir: server
    buildCommand: npm install
    startCommand: npm run dev
    envVars:
      - key: DATABASE_URL
        value: file:./dev.db

  - type: web
    name: watch-inventory-client
    env: static
    rootDir: client
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        value: https://watch-inventory-server.onrender.com