services:
  - type: web
    name: watchdealer-server
    env: node
    buildCommand: npm install
    startCommand: NODE_ENV=production npm run dev
    envVars:
      - key: DATABASE_URL
        value: file:./dev.db
      - key: PORT
        value: 10000

  - type: web
    name: watchdealer-client
    env: static
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: client/dist
    envVars:
      - key: VITE_API_URL
        value: https://watchdealer-server.onrender.com